### ISSUE TITLE
libicui18n.60 missing on Mac for dump_site mode

### ISSUE THREAD

**Issue by groeneveld** [hrenfroe/yahoo-groups-backup#3]
I believe I installed all the dependencies correctly but there appears to be something missing. IDK if this is something with MacOS or some other component.

Command:
python3 yahoo-groups-backup.py dump_site mygroup dump

Error:
dyld: Library not loaded: /usr/local/opt/icu4c/lib/libicui18n.60.dylib
  Referenced from: /usr/local/bin/node
  Reason: image not found
 Rendering templates...
Rendering config file...
Traceback (most recent call last):
  File "yahoo-groups-backup.py", line 129, in <module>
    main()
  File "yahoo-groups-backup.py", line 125, in main
    arguments, cfg_args)
  File "yahoo-groups-backup.py", line 103, in invoke_subcommand
    return module.command(args)
  File "/Users/markgroeneveld/yahoo-groups-backup/yahoo_groups_backup/subcommands/dump_site.py", line 334, in command
    ds.run()
  File "/Users/markgroeneveld/yahoo-groups-backup/yahoo_groups_backup/subcommands/dump_site.py", line 317, in run
    self.render_config()
  File "/Users/markgroeneveld/yahoo-groups-backup/yahoo_groups_backup/subcommands/dump_site.py", line 216, in render_config
    'lastMessageTime': self.db.get_latest_message().get('postDate'),
  File "/Users/markgroeneveld/yahoo-groups-backup/yahoo_groups_backup/backup_db.py", line 91, in get_latest_message
    return next(self.yield_all_messages())
StopIteration

**Comment by hrenfroe** [comment]
You may need to install icu4c via Homebrew. I'm not sure whether that'll create `/usr/local/opt/icu4c/lib/libicui18n.60.dylib`, but start there. If that takes care of it, I'll mention it as a prereq.

**Comment by groeneveld** [comment]
It turns out it was a version problem "brew upgrade icu4c" fixed the issue.
