### ISSUE TITLE
Static site dump is non-functional

### ISSUE THREAD

**Issue by groeneveld** [hrenfroe/yahoo-groups-backup#9]
I got the dump_site working and it's downloaded a copy of the site. But the static site is largely non-functional.

In Firefox and Safari the search function doesn't work at all, the date selection bar on the index doesn't do anything, and often when I click page numbers or the next or back buttons, nothing happens.

**Comment by hrenfroe** [comment]
Did you encounter any errors while dumping the site? I've just tested locally, and the features you mentioned are all working for me.

**Comment by groeneveld** [comment]
Ah, it did throw:
"Stringifying...
There was an error: RangeError: Maximum call stack size exceeded
    at JSON.stringify (<anonymous>)
    at Object.storeCompressed (/Users/markgroeneveld/yahoo-groups-backup/yahoo_groups_backup/subcommands/LocalJSONP.js:89:22)
    at /Users/markgroeneveld/yahoo-groups-backup/yahoo_groups_backup/subcommands/generate_search_index.js:57:23
Dumping group files...
Site is ready in 'dump'!

NOTE: Failed to render the following messages from the raw email
data. They may not have rendered properly."

Then listed a few hundred message numbers.

**Comment by hrenfroe** [comment]
I haven't seen the `Maximum call stack size exceeded` error before. Sounds like one of the saved messages is malformed in such a way as to cause the JSON parser to get stuck in infinite recursion. Can you share the message if you can track down the culprit?

I have seen the "Failed to render" error before, and spot-checked those IDs in the dumped site. Each message I checked shows up fine in the dump, so I'm not sure what's up with that error.
